---
- name: Converge
  hosts: all
  gather_facts: True
  vars_files:
    - ../_shared/common-vars.yml
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "demo"
        compose_stack_name: "demo-extcfg"
        compose_stack_state: "present"
        compose_stack_expose_ports: "{{ global_compose_stack_expose_ports }}"
        compose_stack_config:
          nginx:
            external_configs: true
            configs:
              - source: "/tmp/external-configs/custom-index.html.j2"
                target: "/usr/share/nginx/html/index.html"
                uid: "0"
                gid: "0"
                mode: "0644"
...
