---
# destroy.yml
- name: "stack ({{ stack.name }}) | check if app dir exists"
  ansible.builtin.stat:
    path: "{{ stack.dst_dir }}"
  register: stack_dst_dir_stat

- name: "stack ({{ stack.name }}) | stop and remove compose stack"
  community.docker.docker_compose_v2:
    project_src:    "{{ stack.dst_dir }}"
    state:          "absent"
    remove_images:  "{{ stack.destroy.remove_images }}"
    remove_volumes: "{{ stack.destroy.remove_volumes }}"
  when:
    - stack_dst_dir_stat.stat.isdir is defined
    - stack_dst_dir_stat.stat.isdir

- name: "stack ({{ stack.name }}) | remove .env files"
  ansible.builtin.file:
    path: "{{ stack.dst_dir }}/.env.{{ svc_data.name }}"
    state: "absent"
  loop: "{{ services }}"
  loop_control:
    loop_var: svc_data
  when:
    - stack_dst_dir_stat.stat.isdir is defined
    - stack_dst_dir_stat.stat.isdir
    - svc_data.environment is defined
    - svc_data.environment is mapping

- name: "stack ({{ stack.name }}) | remove app directory"
  ansible.builtin.file:
    path:  "{{ stack.dst_dir }}"
    state: "absent"

...