---
# destroy.yml
- name: "compose_stack ({{ compose_stack_name }}) | check if app dir exists"
  ansible.builtin.stat:
    path: "{{ compose_stack_dst_dir }}"
  register: compose_stack_dst_dir_stat

- name: "compose_stack ({{ compose_stack_name }}) | stop and remove compose stack"
  community.docker.docker_compose_v2:
    project_src:    "{{ compose_stack_dst_dir }}"
    state:          "absent"
    remove_images:  "{{ compose_stack_remove_images_on_destroy }}"
    remove_volumes: "{{ compose_stack_remove_volumes_on_destroy }}"
  when: 
    - compose_stack_dst_dir_stat.stat.isdir is defined
    - compose_stack_dst_dir_stat.stat.isdir

- name: "compose_stack ({{ compose_stack_name }}) | remove app directory"
  ansible.builtin.file:
    path:  "{{ compose_stack_dst_dir }}"
    state: "absent"

- name: "compose_stack ({{ compose_stack_name }}) | remove networks"
  community.docker.docker_network:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ compose_stack_networks }}"
  when: 
    - compose_stack_manage_networks
    - not compose_stack_skip_delete_networks_on_destroy

...