---

- include_tasks: validate.yml

- ansible.builtin.include_vars:
    file: "{{ stack.type }}.yml"

- name: Include stack-specific validation
  include_tasks: "validate-{{ stack.type }}.yml"
  when: lookup('first_found', dict(files=['validate-' + stack.type + '.yml'], paths=[role_path + '/tasks'], skip=true)) != ''

- include_tasks: create.yml
  when: stack.state == "present"

- include_tasks: destroy.yml
  when: stack.state == "absent"

...