---
# tasks file for ansible-role-compose-stack
- name: compose_stack ({{app}}) | create app dir
  ansible.builtin.file:
    path: "{{ app_dst_dir }}"
    state: directory
    mode: '0755'
  when:
    - app_state == "present"

- name: compose_stack ({{app}}) | render compose.yml 
  ansible.builtin.template:
    src: "{{ compose_src_file }}"
    dest: "{{ app_dst_dir }}/compose.yml"
    mode: '0644'
  when:
    - app_state == "present"
  notify: restart compose stack

- name: compose_stack ({{app}}) | copy app data"
  ansible.builtin.copy:
    src: "{{ src_app_data }}/"
    dest: "{{ dst_app_data }}/"
    owner: "{{ app_file_owner }}"
    group: "{{ app_file_owner }}"
    mode: '0644'
    directory_mode: '0744'
  when:
    - app_state == "present"
    - app_copy_data
  notify: restart compose stack

- name: compose_stack ({{app}}) | start compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_dst_dir }}"
    state: present
  when:
    - app_state == "present"

- name: compose_stack ({{ app }}) | stop and remove compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_dst_dir }}"
    state: absent
  when: app_state == "absent"

- name: compose_stack ({{ app }}) | remove app directory
  ansible.builtin.file:
    path: "{{ app_dst_dir }}"
    state: absent
  when: app_state == "absent"
