---

- include_tasks: validate.yml

- ansible.builtin.include_vars:
    file: "{{ stack.type }}.yml"

- include_tasks: create.yml
  when: stack.state == "present"

- include_tasks: destroy.yml
  when: stack.state == "absent"

...