---

- include_tasks: validate.yml

- ansible.builtin.include_vars:
    file: "{{ role_path }}/defaults/{{ stack.name }}.yml"

- include_tasks: create.yml
  when: stack.state == "present"

- include_tasks: destroy.yml
  when: stack.state == "absent"

...