---
# Stack-specific validation for actions-runner stack

- name: Validate actions-runner stack config - github_runner settings
  ansible.builtin.assert:
    that:
      - compose_stack_config.github_runner is defined
      - compose_stack_config.github_runner.github_organization is defined
      - compose_stack_config.github_runner.github_organization | length > 0
      - compose_stack_config.github_runner.github_access_token is defined
      - compose_stack_config.github_runner.github_access_token | length > 0
      - compose_stack_config.github_runner.runner_name is defined
      - compose_stack_config.github_runner.runner_name | length > 0
    fail_msg: |
      GitHub Actions runner configuration is required for actions-runner stack.
      Please provide:
        compose_stack_config:
          github_runner:
            github_organization: "your-github-org"
            github_access_token: "your-pat-token"
            runner_name: "unique-runner-name"
            runner_labels: "self-hosted,linux,x64"  # optional, defaults to "self-hosted,linux,x64"

      IMPORTANT: The GitHub access token must have the following scopes:
        - repo (Full control of private repositories)
        - admin:org (Full control of orgs and teams, read and write org projects)
    success_msg: "GitHub Actions runner configuration validated successfully"
  when: stack.state == "present"
  no_log: true
...
