---
# Stack-specific validation for netbird stack

- name: Validate netbird stack config
  ansible.builtin.assert:
    that:
      - compose_stack_config.netbird is defined
      - compose_stack_config.netbird.setup_key is defined
      - compose_stack_config.netbird.setup_key | length > 0
      - compose_stack_config.netbird.hostname is defined
      - compose_stack_config.netbird.hostname | length > 0
    fail_msg: |
      Netbird stack requires setup_key and hostname.
      Example configuration:
        compose_stack_config:
          netbird:
            setup_key: "your-netbird-setup-key"
            hostname: "my-server-name"
    success_msg: "Netbird configuration validated successfully"
  when: stack.state == "present"
  no_log: true
...
