---
# Stack-specific validation for actions stack

- name: Validate actions stack config - actions settings
  ansible.builtin.assert:
    that:
      - compose_stack_config.actions is defined
      - compose_stack_config.actions.github_organization is defined
      - compose_stack_config.actions.github_organization | length > 0
      - compose_stack_config.actions.github_access_token is defined
      - compose_stack_config.actions.github_access_token | length > 0
      - compose_stack_config.actions.runner_name is defined
      - compose_stack_config.actions.runner_name | length > 0
    fail_msg: |
      GitHub Actions runner configuration is required for actions stack.
      Please provide:
        compose_stack_config:
          actions:
            runner_scope: "org"  # optional: "org" (default) or "repo"
            github_organization: "your-github-org"
            github_repository: "your-repo"  # required only when runner_scope is "repo"
            github_access_token: "your-pat-token"
            runner_name: "unique-runner-name"
            runner_labels: "self-hosted,linux,x64"  # optional, defaults to "self-hosted,linux,x64"

      IMPORTANT: GitHub access token scope requirements depend on runner_scope:

        Organization-level (runner_scope: "org" - default):
          - Token scope required: admin:org (Full control of orgs and teams)
          - Runner available to: All repositories in the organization

        Repository-level (runner_scope: "repo"):
          - Token scope required: repo (Full control of private repositories)
          - Runner available to: Single repository only
          - Must specify github_repository when using this scope

        CRITICAL: Using the wrong token scope will result in 404 errors during runner registration!
    success_msg: "GitHub Actions runner configuration validated successfully"
  when: stack.state == "present"
  no_log: true

- name: Validate actions stack config - repository required for repo scope
  ansible.builtin.assert:
    that:
      - compose_stack_config.actions.github_repository is defined
      - compose_stack_config.actions.github_repository | length > 0
    fail_msg: |
      GITHUB_REPOSITORY is required when runner_scope is set to "repo".
      Please provide:
        compose_stack_config:
          actions:
            runner_scope: "repo"
            github_repository: "your-repo-name"

      Note: Repository name only, not the full URL (e.g., "my-repo" not "github.com/org/my-repo")
    success_msg: "Repository configuration validated successfully for repo-scoped runner"
  when:
    - stack.state == "present"
    - compose_stack_config.actions.runner_scope is defined
    - compose_stack_config.actions.runner_scope == "repo"
  no_log: true
...
