---
- name: Cleanup
  hosts: all
  gather_facts: True
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "netbird"
        compose_stack_name: "netbird-dev"
        compose_stack_state: "absent"
        compose_stack_additional_networks: []  # Netbird doesn't need additional networks
        compose_stack_destroy_remove_volumes: true
        compose_stack_destroy_remove_images: "local"
        compose_stack_config:
          netbird:
            setup_key: "{{ lookup('env', 'NETBIRD_SETUP_KEY') | default('cleanup-placeholder', true) }}"
  post_tasks:
    - name: Include shared volume cleanup tasks
      ansible.builtin.include_tasks: ../_shared/cleanup-volumes.yml
...
