---
- name: Converge
  hosts: all
  gather_facts: True
  vars_files:
    - ../_shared/common-vars.yml
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "netbird"
        compose_stack_name: "netbird-dev"
        compose_stack_state: "present"
        compose_stack_additional_networks: []  # Netbird doesn't need additional networks
        compose_stack_config:
          netbird:
            setup_key: "{{ lookup('env', 'NETBIRD_SETUP_KEY') }}"
            hostname: "netbird-test-node"
...
