---
driver:
  name: docker
platforms:
  # see this file for all options of the docker driver:
  #   ~/.venv_cnns/lib/python3.12/site-packages/molecule_plugins/docker/driver.py
  - name: molecule-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    privileged: true
    dockerfile: ../_shared/Dockerfile.j2
    build_image: true
    pre_build_image: false # set to true if image should not be built
    keep_volumes: false
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    cleanup: cleanup.yml
    side_effect: ../_shared/cleanup-misc.yml
    verify: verify.yml
role_name_check: 1
scenario:
  name: registry
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - side_effect  # Cleanup misc artefacts
    - destroy
...
