---
- name: Cleanup
  hosts: all
  gather_facts: True
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "demo"
        compose_stack_name: "demo-dev"
        compose_stack_state: "absent"
  post_tasks:
    - name: Remove all unnamed (dangling) Docker volumes
      ansible.builtin.command: docker volume prune -f
      changed_when: "'Total reclaimed space' in prune_result.stdout"
      register: prune_result

    - name: Remove unused Docker networks
      ansible.builtin.command: docker network prune -f
      register: network_prune_result
      changed_when: "'Deleted Networks:' in network_prune_result.stdout"
...
