---
- name: Converge
  hosts: all
  gather_facts: True
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "demo"
        compose_stack_name: "demo-dev"
        compose_stack_domain: "example.lan"
        compose_stack_state: "present"
...
