---
- name: Verify
  hosts: all
  gather_facts: False
  roles:

  tasks:
    # Nginx-demo tests
    - name: Check nginx HTTP response
      ansible.builtin.uri:
        url: "http://host.docker.internal:37000"
        return_content: true
      register: nginx_response

    - name: Debug nginx response
      ansible.builtin.debug:
        var: nginx_response.content

    - name: Verify nginx status code
      ansible.builtin.assert:
        that:
          - nginx_response.status == 200
        fail_msg: "Nginx did not return HTTP 200 OK"
        success_msg: "Nginx returned HTTP 200 OK"

    - name: Verify nginx content
      ansible.builtin.assert:
        that:
          - nginx_response.content is search('deployed by the.*compose-stack.*ansible role')
        fail_msg: "Nginx content verification failed! Expected string not found."
        success_msg: "Nginx is serving the expected content."

    # Docker network tests
    - name: Check demo network exists
      ansible.builtin.command: docker network inspect demo
      register: nginx_network
      changed_when: false

    - name: Verify demo network exists
      ansible.builtin.assert:
        that:
          - nginx_network.rc == 0
        fail_msg: "demo network does not exist"
        success_msg: "demo network exists"

    # Docker compose stack tests
    - name: Check demo-dev compose stack status
      ansible.builtin.command: docker compose -f /opt/apps/demo-dev/compose.yml ps
      register: nginx_stack
      changed_when: false

    - name: Verify demo-dev stack is running
      ansible.builtin.assert:
        that:
          - "'demo' in nginx_stack.stdout"
        fail_msg: "demo-dev stack is not running properly"
        success_msg: "demo-dev stack is running"
...
