---
- name: Verify Demo Stack
  hosts: all
  gather_facts: False
  vars:
    compose_stack_name: "demo-dev"
  tasks:
    - name: Include shared verification tasks
      ansible.builtin.include_tasks: ../shared/verify-common.yml
...
