---
services:
  - name: "actions"
    build:
      context: "./build"
      dockerfile: "Dockerfile"

    healthcheck:
      test: ["CMD-SHELL", "test -f /actions-runner/.runner && pgrep -f 'Runner.Listener' > /dev/null || exit 1"]
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "60s"

    environment:
      RUNNER_SCOPE: "{{ compose_stack_config.github_runner.runner_scope | default('org') }}"
      GITHUB_ORGANIZATION: "{{ compose_stack_config.github_runner.github_organization }}"
      GITHUB_REPOSITORY: "{{ compose_stack_config.github_runner.github_repository | default('') }}"
      GITHUB_ACCESS_TOKEN: "{{ compose_stack_config.github_runner.github_access_token }}"
      RUNNER_NAME: "{{ compose_stack_config.github_runner.runner_name }}"
      RUNNER_LABELS: "{{ compose_stack_config.github_runner.runner_labels | default('self-hosted,linux,x64') }}"
...
