---
services:
  - name: "github-runner"
    build:
      context: "./build"
      dockerfile: "Dockerfile"

    stop_grace_period: "30s"

    environment:
      GITHUB_ORGANIZATION: "{{ compose_stack_config.github_runner.github_organization }}"
      GITHUB_ACCESS_TOKEN: "{{ compose_stack_config.github_runner.github_access_token }}"
      RUNNER_NAME: "{{ compose_stack_config.github_runner.runner_name }}"
      RUNNER_LABELS: "{{ compose_stack_config.github_runner.runner_labels | default('self-hosted,Linux,X64') }}"
...
