---
services:
  - name: "grafana"
    image: "grafana/grafana-oss:11.5.1"
    ports:
      - "37011:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: "30s"
      timeout: "10s"
      retries: 3
      start_period: "40s"
    labels:
      traefik:
        enabled: true
        pattern: "default"
      raw: []
    volumes:
      - "grafana-data:/var/lib/grafana"
    depends_on:
      - "influxdb"

  - name: "influxdb"
    image: "influxdb:1.8.3"
    ports:
      - "37012:8086"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: "30s"
      timeout: "10s"
      retries: 3
      start_period: "20s"
    volumes:
      - "influxdb-data:/var/influxdb/data"
...