---
services:
  - name: "grafana"
    image: "grafana/grafana-oss:11.5.1"
    ports:
      - "37011:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: "30s"
      timeout: "10s"
      retries: 3
      start_period: "40s"
    environment:
      GF_SECURITY_ADMIN_USER: "{{ compose_stack_config.grafana.admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ compose_stack_config.grafana.admin_password }}"
    labels:
      traefik:
        enabled: true
        pattern: "default"
      raw: []
    configs:
      - source: "datasources.yaml"
        target: "/etc/grafana/provisioning/datasources/datasources.yaml"
        mode: "0644"
      - source: "dashboard-provider.yaml"
        target: "/etc/grafana/provisioning/dashboards/default.yaml"
        mode: "0644"
      - source: "dashboard-isp-checker.json"
        target: "/etc/grafana/provisioning/dashboards/isp-checker.json"
        mode: "0644"
      - source: "dashboard-prometheus-windowsexporter.json"
        target: "/etc/grafana/provisioning/dashboards/prometheus-windowsexporter.json"
        mode: "0644"
      - source: "dashboard-isp-public-ip-info.json"
        target: "/etc/grafana/provisioning/dashboards/isp-public-ip-info.json"
        mode: "0644"
    volumes:
      - "grafana-data:/var/lib/grafana"
    depends_on:
      - "influxdb"
      - "prometheus"
      - "telegraf"

  - name: "influxdb"
    image: "influxdb:1.8.3"
    ports:
      - "37012:8086"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: "30s"
      timeout: "10s"
      retries: 3
      start_period: "20s"
    environment:
      INFLUXDB_DB: "{{ compose_stack_config.influxdb.database }}"
      INFLUXDB_ADMIN_USER: "{{ compose_stack_config.influxdb.admin_user }}"
      INFLUXDB_ADMIN_PASSWORD: "{{ compose_stack_config.influxdb.admin_password }}"
    volumes:
      - "influxdb-data:/var/influxdb/data"

  - name: "telegraf"
    image: "telegraf:1.33"
    healthcheck:
      test: ["CMD-SHELL", "telegraf --test --config /etc/telegraf/telegraf.conf 2>&1 | grep -q 'inputs' || exit 1"]
      interval: "30s"
      timeout: "10s"
      retries: 3
      start_period: "30s"
    environment:
      INFLUXDB_HOST: "{{ stack.name }}-influxdb"
      INFLUXDB_DATABASE: "{{ compose_stack_config.influxdb.database }}"
      INFLUXDB_USER: "{{ compose_stack_config.influxdb.admin_user }}"
      INFLUXDB_PASSWORD: "{{ compose_stack_config.influxdb.admin_password }}"
    configs:
      - source: "telegraf.conf"
        target: "/etc/telegraf/telegraf.conf"
        mode: "0644"
    depends_on:
      - "influxdb"

  - name: "prometheus"
    image: "prom/prometheus:v2.46.0"
    ports:
      - "37013:9090"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: "30s"
      timeout: "10s"
      retries: 3
      start_period: "30s"
    labels:
      traefik:
        enabled: true
        pattern: "default"
      raw: []
    configs:
      - source: "prometheus.yml"
        target: "/etc/prometheus/prometheus.yml"
        mode: "0644"
    volumes:
      - "prometheus:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
...