---
services:
  - name: "{{ stack.name }}-grafana"
    image: "grafana/grafana-oss:11.5.1"

    ports:
      - "37005:3000"

    labels:
      traefik:
        enabled: true
        pattern: "default"
      raw: []

  - name: "{{ stack.name }}-influxdb"
    image: "influxdb:1.8.3"

    ports:
      - "8086:8086"
...