---
- name: Prepare
  hosts: all
  gather_facts: False
  tasks:
    - name: Create Docker networks for actions-runner stack
      community.docker.docker_network:
        name: "{{ item }}"
        driver: bridge
        state: present
      loop:
        - actions-runner-dev
...
