---
# Shared verification tasks for all molecule scenarios
# This file verifies that all containers in a compose stack are healthy
#
# Required variables (set in scenario verify.yml):
#   - compose_stack_name: The name of the stack (e.g., "demo-dev", "grafana-dev")
#
# Usage in scenario verify.yml:
#   - name: Include shared verification tasks
#     ansible.builtin.include_tasks: ../shared/verify-common.yml

- name: "Wait for all containers in {{ compose_stack_name }} to become healthy"
  ansible.builtin.command: docker compose -f /opt/apps/{{ compose_stack_name }}/compose.yml ps --format json
  register: compose_stack_health
  changed_when: false
  until: >
    compose_stack_health.stdout_lines | map('from_json')
    | selectattr('Health', 'defined')
    | map(attribute='Health')
    | reject('equalto', 'healthy')
    | list | length == 0
  retries: 30
  delay: 2

- name: "Verify all services are healthy in {{ compose_stack_name }} stack"
  ansible.builtin.assert:
    that:
      - compose_stack_health.stdout_lines | map('from_json') | map(attribute='Health') | reject('equalto', 'healthy') | list | length == 0
    fail_msg: "Not all services are healthy in {{ compose_stack_name }} stack"
    success_msg: "All services are healthy in {{ compose_stack_name }} stack"

...
