---
- name: Cleanup
  hosts: all
  gather_facts: True
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "actions"
        compose_stack_name: "actions-dev"
        compose_stack_state: "absent"
  post_tasks:
    - name: Include shared volume cleanup tasks
      ansible.builtin.include_tasks: ../_shared/cleanup-volumes.yml
...
