---
- name: Prepare
  hosts: all
  gather_facts: False
  tasks:
    - name: Create Docker networks for actions stack
      community.docker.docker_network:
        name: "{{ item }}"
        driver: bridge
        state: present
      loop:
        - actions-dev
        - traefik-dev # not needed, but required by the test
...
