---
- name: Cleanup
  hosts: all
  gather_facts: True
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "grafana"
        compose_stack_name: "grafana-dev"
        compose_stack_state: "absent"
        compose_stack_config:
          influxdb:
            database: "monitoring"
            admin_user: "admin"
            admin_password: "test_password"
          grafana:
            admin_user: "admin"
            admin_password: "test_password"
  post_tasks:
    - name: Include shared volume cleanup tasks
      ansible.builtin.include_tasks: ../_shared/cleanup-volumes.yml
...
