---
- name: Converge
  hosts: all
  gather_facts: True
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "grafana"
        compose_stack_name: "grafana-dev"
        compose_stack_domain: "example.lan"
        compose_stack_state: "present"
        compose_stack_additional_networks:
          - traefik-dev
...
