---
- name: Converge
  hosts: all
  gather_facts: True
  vars_files:
    - ../group_vars/all.yml
  roles:
    - role: cloudnonsense.compose_stack
      vars:
        compose_stack_type: "grafana"
        compose_stack_name: "grafana-dev"
        compose_stack_state: "present"
        compose_stack_config:
          influxdb:
            database: "monitoring"
            admin_user: "admin"
            admin_password: "test_password"
          grafana:
            admin_user: "admin"
            admin_password: "test_password"
...
