---
- name: Verify
  hosts: all
  gather_facts: False
  tasks:
    - name: Check grafana-dev compose stack status
      ansible.builtin.command: docker compose -f /opt/apps/grafana-dev/compose.yml ps
      register: compose_stack
      changed_when: false

    - name: Verify compose stack has healthy containers
      ansible.builtin.assert:
        that:
          - "compose_stack.stdout is search('grafana.*\\(healthy\\)')"
          - "compose_stack.stdout is search('influxdb.*\\(healthy\\)')"
          - "compose_stack.stdout is search('telegraf.*\\(healthy\\)')"
          - "compose_stack.stdout is search('prometheus.*\\(healthy\\)')"
        fail_msg: "Not all expected services are healthy in grafana-dev stack"
        success_msg: "All expected services are healthy"
